eureka_hostname: service-registry

service_hostname: admin-service

# Production environment
#mongodb_hostname: shop-db
#mongodb_database_name: adminDB

# Development environment
mongodb_hostname: localhost
mongodb_database_name: testWorkingDB

# Test environment
#mongodb_hostname: shop-db
#mongodb_database_name: testAdminDB

# Eureka properties
#eureka:
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://${eureka_hostname}:8761/eureka
#  instance:
#    hostname: ${service_hostname}

# Server properties
server:
  port: 8090

# Application properties
spring:
  application:
    name: ADMIN-SERVICE
# MongoDB properties
  data:
    mongodb:
      database: ${mongodb_database_name}
      host: ${mongodb_hostname}
      port: 27017
  config:
    import: optional:settings.yml
